#pragma once
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>
#include <Target.h>
#include <CameraInfo.h>
#include <vision/VisionPipeline.h>
#include <networktables/NetworkTableInstance.h>

namespace grip {

/**
* A representation of the different types of blurs that can be used.
*
*/
enum BlurType {
	BOX, GAUSSIAN, MEDIAN, BILATERAL
};
/**
* GoalPipeline class.
* 
* An OpenCV pipeline generated by GRIP.
*/
class GoalPipeline : public VisionPipeline {
	private:
		CameraInfo mCameraInfo;
		cv::Mat blurOutput;
		cv::Mat hsvThresholdOutput;
		std::vector<std::vector<cv::Point> > findContoursOutput;
		std::vector<std::vector<cv::Point> > filterContoursOutput;
		std::vector<std::vector<cv::Point> > approxPolyOutput;
		std::vector<Target> targetsOutput;
		void blur(cv::Mat &, BlurType &, double , cv::Mat &);
		void hsvThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);
		void findContours(cv::Mat &, bool , std::vector<std::vector<cv::Point> > &);
		void filterContours(std::vector<std::vector<cv::Point> > &, double , double , double , double , double , double , double [], double , double , double , double , std::vector<std::vector<cv::Point> > &);
		void approximatePolygons(std::vector<std::vector<cv::Point>>& contours, std::vector<std::vector<cv::Point>>& output, double minDistancePerSide);
		void generateTargets(std::vector<std::vector<cv::Point>>& polygons, std::vector<Target>& targetsOutput);

	public:
		GoalPipeline();
		void Process(cv::Mat& source0);
		cv::Mat* GetBlurOutput();
		cv::Mat* GetHsvThresholdOutput();
		std::vector<std::vector<cv::Point> >* GetFindContoursOutput();
		std::vector<std::vector<cv::Point> >* GetFilterContoursOutput();
		void outputToSmartDashboard(nt::NetworkTableInstance networkTableInst);
		
};


} // end namespace grip


